#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Disable the whole bunch of useless git aliases
zstyle ':prezto:module:git:alias' skip 'yes'
alias kraken='open -na "GitKraken" --args -p $(pwd)'


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Ajout de ~/bin au PATH
export PATH=$HOME/bin:$PATH


# Use TextMate for all your editing needs
export EDITOR='mate -w'


# thefuck command correction
eval $(thefuck --alias)

# Always use yarn inside a docker container (not ready yet)
# alias yarn='docker run --rm -v $(pwd):/app -w /app lahautesociete/nodejs-ci:8 yarn'

# Load aliases file
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/alias" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/alias"
fi

# Load environment variables file
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/env" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/env"
fi
