#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Disable the whole bunch of useless git aliases
zstyle ':prezto:module:git:alias' skip 'yes'


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Always use yarn inside a docker container (not ready yet)
# alias yarn='docker run --rm -v $(pwd):/app -w /app lahautesociete/nodejs-ci:8 yarn'

# Load aliases file
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/alias" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/alias"
fi

# Load environment variables file
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/env" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/env"
fi

# Load secret (uncommited) environment variables file
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/env.secret" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/env.secret"
fi

# Load brew-related environment variables
if [[ -f $HOME/.brew-env ]]; then
    source $HOME/.brew-env
fi

# thefuck command correction
eval $(thefuck --alias)
