#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Ajout de ~/bin au PATH
export PATH=$HOME/bin:$PATH

# TextMate comme editeur
export SVN_EDITOR='mate -w'
export EDITOR='mate -w'

# thefuck command correction
eval "$(thefuck --alias)"
